apiVersion: v2
description: A Helm chart for deploying OTS
name: ots
version: 1.8.4
# renovate: datasource=docker depName=ghcr.io/luzifer/ots
appVersion: '1.21.5'
annotations:
  artifacthub.io/links: |
    - name: Helm Chart
      url: https://github.com/ContinuousSecurityTooling/ots-helm-chart
    - name: Application
      url: https://github.com/Luzifer/ots
