apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ots.fullname" . }}
  labels:
    {{- include "ots.labels" . | nindent 4 }}
data:
  customize.yml: |
  {{- range $k, $v := .Values.customizations }}
    {{ $k }}: {{ tpl $v $ }}
  {{- end }}
