apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ots.fullname" . }}
  labels:
    {{- include "ots.labels" . | nindent 4 }}
data:
  customize.yml: 
    {{- .Values.customizations | toYaml | nindent 4 }}