{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ots.fullname" . }}-redis
  labels:
    {{- include "ots.labels" . | nindent 4 }}
spec:
  {{- if .Values.peristence.storageClass -}}
  storageClassName: {{ .Values.peristence.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.peristence.volumeSize }}
 {{- end }}