apiVersion: v1
kind: Service
metadata:
  name: {{ include "ots.fullname" . }}
  labels:
    {{- include "ots.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: ots-tcp
      protocol: TCP
      name: app
  selector:
    {{- include "ots.selectorLabels" . | nindent 4 }}