env:
  - name: SOME_ENV
    value: some value
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: ca-issuer
  hostname: ots2.m13t.de
  tls:
    secretName: ots-tls
customizations:
  metricsAllowedSubnets:
    # default to Pod IPs
    - 127.0.0.1/24
    - 10.0.0.0/8
metrics:
  enabled: true
persistence:
  storageClass: longhorn
  volumeSize: 5Gi