name: Build

on:
  pull_request:
  merge_group:
  push:
    branches:
      - develop

jobs:
  chart:
    name: 'Build and Test Helm Chart'
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.11.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Helm Chart Testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config .ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct --config .ct.yaml lint --target-branch ${{ github.event.repository.default_branch }}
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@v1.9.0
        with:
          config: .github/kind.cfg.yaml
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Prom Stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install - no further args)
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install - with further args)
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --helm-extra-set-args "--namespace monitoring -f chart/ci/values.yaml"
        if: steps.list-changed.outputs.changed == 'true'
